### ISSUE TITLE
New BSgenome -  C3H/HeJ Mus musculus

### ISSUE THREAD

**Issue by ghost** [Bioconductor/BSgenome#25]
Dear,

I am trying to run the MutationalPatterns and load the C3H/HeJ Mus musculus genome using BSgenome. However, it is not available in the BSgenome library. The genome is available through the [link](http://ftp.ensembl.org/pub/release-105/fasta/mus_musculus_c3hhej/dna/).

I am getting the following error, when I try to integrate in myself as it is said in the the following [tutorial](https://bioconductor.org/packages/release/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf). UI am just at the first step in  

```
Error in .Call2("new_input_filexp", filepath, PACKAGE = "XVector") : 
  cannot open file ''
```

I am sure that the file is at the exact location.

Best regards,

Ekaterina

**Comment by hpages** [comment]
Please show the command you ran that produced this error and also share any other information that would allow me to reproduce the error like the exact file you downloaded and your seed file. Thanks!

**Comment by ghost** [comment]
Thank you for a fast response:

the genome represents merged fasta files from here - http://ftp.ensembl.org/pub/release-105/fasta/mus_musculus_c3hhej/dna/. I merged them with cat command.  

I couldn't load the file, though I was sure its in that folder I expect it to be I tried to use absolute path to the file but it did not work.
```
> library(Biostrings)
> setwd("M:/Data/Analysis")
> file <- system.file("extdata", "Mus_musculus_c3hhej.C3H_HeJ_v1.dna.fa.gz", package="BSgenome")
> fasta.seqlengths(file)
```

**Comment by hpages** [comment]
Why are you using `system.file()` to access the file? The name of the function is not intuitive but `system.file()` is for accessing files that belong to a package. More precisely it is for files located in the installation folder of a package. I'm pretty sure this is not the case for `Mus_musculus_c3hhej.C3H_HeJ_v1.dna.fa.gz`.

In addition to having a bad name, the function also has a terrible feature: by default it returns an empty string if the file is not found at the specified location, instead of an error:
```
file <- system.file("extdata", "Mus_musculus_c3hhej.C3H_HeJ_v1.dna.fa.gz", package="BSgenome")
file
# [1] ""
````
Note that `system.file()` has the `mustWork` argument to prevent this. See `?system.file` for more information.

Why not just explicitly set `file` to the path of the FASTA file e.g. with something like:
```
file <- "path/to/the/fasta/file"
```

This is _very_ basic R stuff and you'll need to get familiarized with it before you can effectively perform analyses with Bioconductor.

H.
