### ISSUE TITLE
Error Forging BSgenome Package

### ISSUE THREAD

**Issue by sopeadeniji** [Bioconductor/BSgenome#56]
Hi,
I got some errors and warnings after checking my BSgenome package. Please, could you help with explaining the errors and warnings in check.log? Code written below:
> R CMD build BSgenome.Custulatus.NCBI.bCatUst1.pri.v2
> R CMD check BSgenome.Custulatus.NCBI.bCatUst1.pri.v2_0.0.1.tar.gz

[00check.log](https://github.com/Bioconductor/BSgenome/files/10135857/00check.log)

Best,
S.

**Comment by vjcitn** [comment]
I don't want to bring that log down onto my computer.  Please extract the lines that indicate an error is occurring and place that text into the issue.  Also, please provide the result of sessionInfo() after the error.  Please be sure BiocManager::valid() returns TRUE for your system.

**Comment by sopeadeniji** [comment]
Error line below:
> genome <- BSgenome.Custulatus.NCBI.bCatUst1.pri.v2
> head(seqlengths(genome))
     super_scaffold_1 scaffold_2_arrow_ctg1      super_scaffold_3 
            165774257             124776741             120187523 
     super_scaffold_5 scaffold_4_arrow_ctg1 scaffold_6_arrow_ctg1 
             77026709              76913702              63528738 
> genome[["1"]]
Error in genome[["1"]] : no such sequence
Calls: [[ -> [[
Execution halted
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without index ... ERROR
Re-running with no redirection of stdout/stderr.
* DONE
Status: 2 ERRORs, 2 WARNINGs, 3 NOTEs


> BiocManager::valid()
Bioconductor version '3.16'

  * 4 packages out-of-date
  * 0 packages too new

create a valid installation with

  BiocManager::install(c(
    "BiocParallel", "DelayedArray", "GenomicRanges", "matrixStats"
  ), update = TRUE, ask = FALSE, force = TRUE)

more details: BiocManager::valid()$too_new, BiocManager::valid()$out_of_date

Warning message:
4 packages out-of-date; 0 packages too new

**Comment by hpages** [comment]
> Error in genome[["1"]] : no such sequence

Pretty clear no? This assembly has no sequence named `1`. So your example fails because you are trying to load a sequence that doesn't exist.

You need to modify your example to use a valid sequence name.

See the sequence names in the "Full sequence report" here (in the leftmost column): https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/819/885/GCF_009819885.2_bCatUst1.pri.v2/GCF_009819885.2_bCatUst1.pri.v2_assembly_report.txt

Alternatively, you can get the sequence names with `getChromInfoFromNCBI("GCA_009819885.2")$SequenceName`,  as discussed [here](https://github.com/Bioconductor/GenomeInfoDb/issues/78).

The code used in the example is supplied via the seed file. So you need to modify your seed file and forge the package again.

**Comment by sopeadeniji** [comment]
Thanks Herve, I figured I had to correct the seed file. How about the "LaTeX errors when creating PDF version"?

**Comment by hpages** [comment]
> How about the "LaTeX errors when creating PDF version"?

That's just a WARNING. Maybe something is wrong with your LaTeX setup? Hard to know without having more details about your OS and LaTeX installation. Anyways, I don't know how much you care about generating the PDF manual, but if you don't care too much, you can always run `R CMD check` with the `--no-manual` flag. As long as this passes with no ERROR or WARNING, you should be good. Even some WARNINGs are acceptable, it all depends on the particular WARNING.

**Comment by sopeadeniji** [comment]
Got it, thanks.

**Comment by hpages** [comment]
Is it ok to close this?

**Comment by sopeadeniji** [comment]
Yes, it is.
